version: 2

sources:
  - name: my_source
    schema: public
    tables:
      - name: seed_data
        description: "Synthetic data for transactions"
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}
